# Site settings
title: Arantxa Morcillo
email: contact@arantxamorcillo.com
description: "Arantxa Morchillo fashion designer profile website"
baseurl: ""
url: "http://www.arantxamorcillo.com"

# Build settings
markdown: kramdown
permalink: pretty
